quarkus.http.port=9090

# Temporal
quarkus.temporal.connection.target=localhost:7233
quarkus.temporal.namespace=default
quarkus.temporal.start-workers=true

# Worker versioning (Strategy 2 — Pinned)
# build-id is set at startup via JVM arg: -Dquarkus.temporal.worker.payment-queue.build-id=<version>
quarkus.temporal.worker.payment-queue.use-build-id-for-versioning=true

# Payment API REST client
quarkus.rest-client.payment-api.url=http://localhost:8089